### ISSUE TITLE
explore_trace_search

### ISSUE THREAD

**Issue by dicook** [huizezhang-sherry/ferrn#1]
- [ ] I don't think the max vals at the second to last and last tries should be connected. I think that the last tries is when the algorithm decides to stop searching. Its arguable that this should be dropped completely. 
- [ ] Make a vertical line indicating the tries of the final index value.
- [ ] Think about making theme_bw, to be consistent with changes likely made to other diagnostic plots.

**Comment by dicook** [comment]
Why does the colour get dark again? Shouldn't this be a linear progression mapped to the iteration number?

**Comment by huizezhang-sherry** [comment]
the last tries is not plotted by `explore_trace_interp()` because no better basis found and hence no interpolation conducted. 

data related to the last try is only used in search-related plots i.e. `explore_trace_search()` and `explore_space_pca()` but not  interpolation related `explore_trace_interp()`

**Comment by dicook** [comment]
Why is it needed in explore_trace_search() then? It seems like its a distraction

**Comment by huizezhang-sherry** [comment]
cause explore_trace_search() is supposed to provide a summary of all the searching points.

So in the plot,  the last iteration should end up hitting the `max.tries`. This can be a preliminary check on if the algorithm finishes in some unexpected ways. 

But other than that,  the last iteration does feel like a big tail to carry everywhere.

**Comment by dicook** [comment]
Why is the max value connected across the interpolation number then? This suggests the focus is on the highest value, and we are exploring that. The highest value for the last step is always lower.

**Comment by huizezhang-sherry** [comment]
Yes, I highlight the highest value with an intention to show the improvement made by each try. 

Connecting the last two highest can be a bit confusing. 

I can remove the geom_line  but still highlight the max, maybe with a larger size = 2?

**Comment by huizezhang-sherry** [comment]
An alternative is to keep the geom_line with the highlighted max but change the last iteration to grey. 

An example plot would be like:

![image](https://user-images.githubusercontent.com/36781502/99493472-5f599500-29c3-11eb-9125-c54a84ca764a.png)

**Comment by huizezhang-sherry** [comment]
implemented in commit 52999d9c3d227fdab33ea9957cfd9c5251a04852

**Comment by dicook** [comment]
The line truncation isn't showing up for me in the current github version:

![image](https://user-images.githubusercontent.com/253191/99604043-b9586a00-2a58-11eb-9d3d-e1fb43dc0cfe.png)

**Comment by huizezhang-sherry** [comment]
The currently github version should work 

``` r
library(ferrn)
holes_1d_better %>% 
  explore_trace_search() + 
  scale_color_botanical(palette = "fern")
```

![](https://i.imgur.com/Iq3onxX.png)

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
