### ISSUE TITLE
explore_trace.R

### ISSUE THREAD

**Issue by dicook** [huizezhang-sherry/ferrn#2]
It should be possible to easily extract the end point at each interpolation. there should be a vertical line drawn each time a new interpolation starts. all other vertical grid lines should be removed.

**Comment by huizezhang-sherry** [comment]
This can be done via `get_interp_last()` function as in 

```
holes_1d_better %>% get_interp_last()
get_interp_last(dplyr::bind_rows(holes_1d_better, holes_1d_geo), group = method)
```

**Comment by dicook** [comment]
The trace plot is looking better: 
![image](https://user-images.githubusercontent.com/253191/99603861-5535a600-2a58-11eb-8a1a-6f3055b0832c.png)

It needs to have vertical lines at each break in the interpolation
