### ISSUE TITLE
Typo in `lead()` argument `default`

### ISSUE THREAD

**Issue by DavisVaughan** [huizezhang-sherry/ferrn#8]
Right here, it should be `defualt` rather than `default`
https://github.com/huizezhang-sherry/ferrn/blob/1ddb8a3bfbf75728b8c94b7488dd157c4514867f/R/explore_space.R#L300

We are working on the next version of dplyr and we are ensuring that we automatically avoid these kinds of typos. This one popped up in a reverse dependency check.

If you could please fix this typo and send in a new release of your package to CRAN, then it would help us release dplyr. Thanks!

**Comment by huizezhang-sherry** [comment]
Thanks! Fixed the typo in 2206789a2e373d88e2229a0a49b9c4747defe1d9 and has submitted to CRAN now.

**Comment by DavisVaughan** [comment]
Thanks!
